# Generated by Django 3.2.6 on 2021-08-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutytModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_title', models.TextField(max_length=1000, verbose_name='Обязанность')),
            ],
            options={
                'ordering': ['duty_title'],
            },
        ),
        migrations.CreateModel(
            name='ManagersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250, verbose_name='Занимаемая должность')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='managers_photos', verbose_name='Фотография')),
                ('private_info', models.TextField(verbose_name='Личное дело / биография')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('email_for_appeals', models.EmailField(max_length=254, verbose_name='E-mail для обращений граждан')),
                ('reception', models.CharField(max_length=250, verbose_name='Прием по личным вопросам')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='OurEmployeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_name', models.CharField(max_length=250, verbose_name='ФИО сотрудника')),
                ('empl_title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('empl_publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('empl_biography', models.TextField(verbose_name='Биография сотрудника')),
            ],
            options={
                'verbose_name': 'Наш сотрудник',
                'verbose_name_plural': 'Наши сотрудники',
                'ordering': ['empl_title'],
            },
        ),
        migrations.CreateModel(
            name='RequirementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_title', models.TextField(max_length=1000, verbose_name='Требование')),
            ],
            options={
                'ordering': ['requirement_title'],
            },
        ),
        migrations.CreateModel(
            name='WelcomedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomed_title', models.TextField(max_length=1000, verbose_name='Приветствуется')),
            ],
            options={
                'ordering': ['welcomed_title'],
            },
        ),
        migrations.CreateModel(
            name='WorkingConditionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_title', models.TextField(max_length=1000, verbose_name='Условие работы')),
            ],
            options={
                'ordering': ['condition_title'],
            },
        ),
        migrations.CreateModel(
            name='VacanciesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=250, verbose_name='Заголовок вакансии')),
                ('salary', models.CharField(max_length=100, verbose_name='Заработная плата')),
                ('work_experience', models.CharField(max_length=250, verbose_name='Опыт работы')),
                ('full_employment', models.CharField(max_length=250, verbose_name='Полная занятость')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('duties', models.ManyToManyField(to='about_stadium_app.DutytModel')),
                ('requirements', models.ManyToManyField(to='about_stadium_app.RequirementModel')),
                ('welcomed', models.ManyToManyField(to='about_stadium_app.WelcomedModel')),
                ('working_conditions', models.ManyToManyField(to='about_stadium_app.WorkingConditionModel')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='EmployeePhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(db_index=True, max_length=250, verbose_name='Название фото')),
                ('photo_image', models.ImageField(upload_to='employees_photos')),
                ('photo_publication_date', models.DateTimeField(auto_now_add=True)),
                ('is_title_image', models.BooleanField(default=False, verbose_name='Фото для заголовка')),
                ('photo_author', models.CharField(default='ФК "Динамо-Минск"', max_length=250, verbose_name='Автор')),
                ('employee_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_stadium_app.ouremployeesmodel', verbose_name='')),
            ],
            options={
                'verbose_name': 'Фотография сотрудников',
                'verbose_name_plural': 'Фотографии сотрудников',
            },
        ),
    ]
