# Generated by Django 3.2.6 on 2021-08-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_title', models.CharField(max_length=250, verbose_name='Наименование услуги')),
                ('adv_unit', models.CharField(max_length=100, verbose_name='Единица измерения')),
                ('adv_tariff_wo_vat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Тариф без НДС')),
                ('adv_tariff_w_vat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Тариф c НДС')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsToDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=250, verbose_name='Название документа')),
                ('document_file', models.FileField(upload_to='documents_to_download', verbose_name='Файл документа')),
            ],
        ),
    ]
