# Generated by Django 3.2.6 on 2021-08-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category_name', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='')),
                ('service_category_description', models.TextField(blank=True, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ServicedescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('service_image', models.ImageField(upload_to='service_title_images', verbose_name='Изображение-обложка услуги')),
                ('service_description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('service_price', models.CharField(max_length=100, verbose_name='Цена услуги')),
                ('service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_app.servicecategorymodel', verbose_name='Категория услуги')),
            ],
        ),
    ]
