# Generated by Django 3.2.6 on 2021-08-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhotosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(db_index=True, max_length=250, verbose_name='Название фото')),
                ('photo_image', models.ImageField(upload_to='news_photos')),
                ('photo_publication_date', models.DateTimeField(auto_now_add=True)),
                ('photo_author', models.CharField(blank=True, default='ФК "Динамо-Минск"', max_length=250, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новостное фото',
                'verbose_name_plural': 'Новостные фото',
                'ordering': ('photo_publication_date',),
            },
        ),
        migrations.CreateModel(
            name='NewsVideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(db_index=True, max_length=250, verbose_name='Название видео')),
                ('video_url', models.URLField(max_length=250, verbose_name='Ссылка на видео на youtube')),
                ('video_publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('video_author', models.CharField(max_length=250, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новостное видео(youtube)',
                'verbose_name_plural': 'Новостные видео(youtube)',
                'ordering': ('video_publication_date',),
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(db_index=True, max_length=250, verbose_name='Новостной заголовок')),
                ('news_content', models.TextField(verbose_name='Новостной контент')),
                ('news_publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации новости')),
                ('news_source', models.CharField(max_length=250, null=True, verbose_name='Источник')),
                ('news_author', models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор')),
                ('news_time_of_reading', models.CharField(default='5 минут', max_length=250, verbose_name='Время чтения')),
                ('news_photos', models.ManyToManyField(related_name='photos', to='news_app.NewsPhotosModel', verbose_name='Новостные фото')),
                ('news_title_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_photo', to='news_app.newsphotosmodel', verbose_name='Главное фото новости')),
                ('news_videos', models.ManyToManyField(to='news_app.NewsVideosModel', verbose_name='Новостные видео')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('news_publication_date',),
            },
        ),
    ]
