# Generated by Django 3.2.6 on 2021-08-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_videos',
            field=models.ManyToManyField(blank=True, to='news_app.NewsVideosModel', verbose_name='Новостные видео'),
        ),
        migrations.AlterField(
            model_name='newsphotosmodel',
            name='photo_image',
            field=models.ImageField(upload_to='news_photos/%Y/%m/%d'),
        ),
    ]
