# Generated by Django 3.2.6 on 2021-08-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_album_title', models.CharField(max_length=50, verbose_name='Название фотоальбома')),
                ('photo_album_title_image', models.ImageField(upload_to='photo_album_title_images', verbose_name='Изображение-обложка фотоальбома')),
                ('date_album_video', models.DateField(auto_now_add=True, verbose_name='Дата создания фотоальбома')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ('photo_album_title',),
            },
        ),
        migrations.CreateModel(
            name='VideoAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_album_title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название видеоальбома')),
                ('video_album_title_image', models.ImageField(upload_to='video_album_title_images', verbose_name='Изображение-обложка видеоальбома')),
                ('video_album_creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания видеоальбома')),
            ],
            options={
                'verbose_name': 'Видеоальбом',
                'verbose_name_plural': 'Видеоальбомы',
                'ordering': ('video_album_title',),
            },
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50, verbose_name='Название видео')),
                ('video_publication_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_bright_moment', models.BooleanField(default=False, verbose_name='Яркие моменты(видео)')),
                ('video_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.videoalbummodel', verbose_name='Альбом видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('video_name',),
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=50, verbose_name='Название фото')),
                ('photo_publication_date', models.DateField(auto_now_add=True, verbose_name='Дата создания фото')),
                ('is_bright_moment', models.BooleanField(default=False, verbose_name='Яркие моменты фото')),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.photoalbummodel', verbose_name='Альбом фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('photo_name',),
            },
        ),
    ]
