# Generated by Django 3.2.6 on 2021-08-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideosModel',
            new_name='VideoModel',
        ),
    ]
